// Code generated by protoc-gen-box. DO NOT EDIT.
// source: diskqueue.proto

package diskqueue

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	tr "github.com/tddhit/box/transport"
	tropt "github.com/tddhit/box/transport/option"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import (
	context1 "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Command_Op int32

const (
	Command_PUSH    Command_Op = 0
	Command_ADVANCE Command_Op = 1
)

var Command_Op_name = map[int32]string{
	0: "PUSH",
	1: "ADVANCE",
}
var Command_Op_value = map[string]int32{
	"PUSH":    0,
	"ADVANCE": 1,
}

func (x Command_Op) String() string {
	return proto.EnumName(Command_Op_name, int32(x))
}
func (Command_Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{13, 0}
}

type Message struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	HashKey              []byte   `protobuf:"bytes,3,opt,name=hashKey,proto3" json:"hashKey,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Message) GetHashKey() []byte {
	if m != nil {
		return m.HashKey
	}
	return nil
}

func (m *Message) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type PushRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	HashKey              []byte   `protobuf:"bytes,3,opt,name=hashKey,proto3" json:"hashKey,omitempty"`
	IgnoreFilter         bool     `protobuf:"varint,4,opt,name=ignoreFilter,proto3" json:"ignoreFilter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushRequest) Reset()         { *m = PushRequest{} }
func (m *PushRequest) String() string { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()    {}
func (*PushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{1}
}
func (m *PushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRequest.Unmarshal(m, b)
}
func (m *PushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRequest.Marshal(b, m, deterministic)
}
func (dst *PushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRequest.Merge(dst, src)
}
func (m *PushRequest) XXX_Size() int {
	return xxx_messageInfo_PushRequest.Size(m)
}
func (m *PushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRequest proto.InternalMessageInfo

func (m *PushRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PushRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PushRequest) GetHashKey() []byte {
	if m != nil {
		return m.HashKey
	}
	return nil
}

func (m *PushRequest) GetIgnoreFilter() bool {
	if m != nil {
		return m.IgnoreFilter
	}
	return false
}

type PushReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushReply) Reset()         { *m = PushReply{} }
func (m *PushReply) String() string { return proto.CompactTextString(m) }
func (*PushReply) ProtoMessage()    {}
func (*PushReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{2}
}
func (m *PushReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushReply.Unmarshal(m, b)
}
func (m *PushReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushReply.Marshal(b, m, deterministic)
}
func (dst *PushReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushReply.Merge(dst, src)
}
func (m *PushReply) XXX_Size() int {
	return xxx_messageInfo_PushReply.Size(m)
}
func (m *PushReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PushReply.DiscardUnknown(m)
}

var xxx_messageInfo_PushReply proto.InternalMessageInfo

type PopRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	NeedAck              bool     `protobuf:"varint,2,opt,name=needAck,proto3" json:"needAck,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PopRequest) Reset()         { *m = PopRequest{} }
func (m *PopRequest) String() string { return proto.CompactTextString(m) }
func (*PopRequest) ProtoMessage()    {}
func (*PopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{3}
}
func (m *PopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PopRequest.Unmarshal(m, b)
}
func (m *PopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PopRequest.Marshal(b, m, deterministic)
}
func (dst *PopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PopRequest.Merge(dst, src)
}
func (m *PopRequest) XXX_Size() int {
	return xxx_messageInfo_PopRequest.Size(m)
}
func (m *PopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PopRequest proto.InternalMessageInfo

func (m *PopRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PopRequest) GetNeedAck() bool {
	if m != nil {
		return m.NeedAck
	}
	return false
}

type PopReply struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PopReply) Reset()         { *m = PopReply{} }
func (m *PopReply) String() string { return proto.CompactTextString(m) }
func (*PopReply) ProtoMessage()    {}
func (*PopReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{4}
}
func (m *PopReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PopReply.Unmarshal(m, b)
}
func (m *PopReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PopReply.Marshal(b, m, deterministic)
}
func (dst *PopReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PopReply.Merge(dst, src)
}
func (m *PopReply) XXX_Size() int {
	return xxx_messageInfo_PopReply.Size(m)
}
func (m *PopReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PopReply.DiscardUnknown(m)
}

var xxx_messageInfo_PopReply proto.InternalMessageInfo

func (m *PopReply) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type AckRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	MsgID                uint64   `protobuf:"varint,2,opt,name=msgID,proto3" json:"msgID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckRequest) Reset()         { *m = AckRequest{} }
func (m *AckRequest) String() string { return proto.CompactTextString(m) }
func (*AckRequest) ProtoMessage()    {}
func (*AckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{5}
}
func (m *AckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckRequest.Unmarshal(m, b)
}
func (m *AckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckRequest.Marshal(b, m, deterministic)
}
func (dst *AckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckRequest.Merge(dst, src)
}
func (m *AckRequest) XXX_Size() int {
	return xxx_messageInfo_AckRequest.Size(m)
}
func (m *AckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AckRequest proto.InternalMessageInfo

func (m *AckRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *AckRequest) GetMsgID() uint64 {
	if m != nil {
		return m.MsgID
	}
	return 0
}

type AckReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckReply) Reset()         { *m = AckReply{} }
func (m *AckReply) String() string { return proto.CompactTextString(m) }
func (*AckReply) ProtoMessage()    {}
func (*AckReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{6}
}
func (m *AckReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckReply.Unmarshal(m, b)
}
func (m *AckReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckReply.Marshal(b, m, deterministic)
}
func (dst *AckReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckReply.Merge(dst, src)
}
func (m *AckReply) XXX_Size() int {
	return xxx_messageInfo_AckReply.Size(m)
}
func (m *AckReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AckReply.DiscardUnknown(m)
}

var xxx_messageInfo_AckReply proto.InternalMessageInfo

type JoinRequest struct {
	RaftAddr             string   `protobuf:"bytes,1,opt,name=raftAddr,proto3" json:"raftAddr,omitempty"`
	NodeID               string   `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{7}
}
func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (dst *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(dst, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetRaftAddr() string {
	if m != nil {
		return m.RaftAddr
	}
	return ""
}

func (m *JoinRequest) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

type JoinReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinReply) Reset()         { *m = JoinReply{} }
func (m *JoinReply) String() string { return proto.CompactTextString(m) }
func (*JoinReply) ProtoMessage()    {}
func (*JoinReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{8}
}
func (m *JoinReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinReply.Unmarshal(m, b)
}
func (m *JoinReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinReply.Marshal(b, m, deterministic)
}
func (dst *JoinReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinReply.Merge(dst, src)
}
func (m *JoinReply) XXX_Size() int {
	return xxx_messageInfo_JoinReply.Size(m)
}
func (m *JoinReply) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinReply.DiscardUnknown(m)
}

var xxx_messageInfo_JoinReply proto.InternalMessageInfo

type LeaveRequest struct {
	NodeID               string   `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRequest) Reset()         { *m = LeaveRequest{} }
func (m *LeaveRequest) String() string { return proto.CompactTextString(m) }
func (*LeaveRequest) ProtoMessage()    {}
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{9}
}
func (m *LeaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRequest.Unmarshal(m, b)
}
func (m *LeaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRequest.Marshal(b, m, deterministic)
}
func (dst *LeaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRequest.Merge(dst, src)
}
func (m *LeaveRequest) XXX_Size() int {
	return xxx_messageInfo_LeaveRequest.Size(m)
}
func (m *LeaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRequest proto.InternalMessageInfo

func (m *LeaveRequest) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

type LeaveReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveReply) Reset()         { *m = LeaveReply{} }
func (m *LeaveReply) String() string { return proto.CompactTextString(m) }
func (*LeaveReply) ProtoMessage()    {}
func (*LeaveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{10}
}
func (m *LeaveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveReply.Unmarshal(m, b)
}
func (m *LeaveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveReply.Marshal(b, m, deterministic)
}
func (dst *LeaveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveReply.Merge(dst, src)
}
func (m *LeaveReply) XXX_Size() int {
	return xxx_messageInfo_LeaveReply.Size(m)
}
func (m *LeaveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveReply.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveReply proto.InternalMessageInfo

type SnapshotRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnapshotRequest) Reset()         { *m = SnapshotRequest{} }
func (m *SnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*SnapshotRequest) ProtoMessage()    {}
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{11}
}
func (m *SnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotRequest.Unmarshal(m, b)
}
func (m *SnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotRequest.Marshal(b, m, deterministic)
}
func (dst *SnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotRequest.Merge(dst, src)
}
func (m *SnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_SnapshotRequest.Size(m)
}
func (m *SnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotRequest proto.InternalMessageInfo

type SnapshotReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnapshotReply) Reset()         { *m = SnapshotReply{} }
func (m *SnapshotReply) String() string { return proto.CompactTextString(m) }
func (*SnapshotReply) ProtoMessage()    {}
func (*SnapshotReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{12}
}
func (m *SnapshotReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotReply.Unmarshal(m, b)
}
func (m *SnapshotReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotReply.Marshal(b, m, deterministic)
}
func (dst *SnapshotReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotReply.Merge(dst, src)
}
func (m *SnapshotReply) XXX_Size() int {
	return xxx_messageInfo_SnapshotReply.Size(m)
}
func (m *SnapshotReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotReply.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotReply proto.InternalMessageInfo

type Command struct {
	Op                   Command_Op `protobuf:"varint,1,opt,name=op,proto3,enum=diskqueue.Command_Op" json:"op,omitempty"`
	Topic                string     `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Data                 []byte     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	HashKey              []byte     `protobuf:"bytes,4,opt,name=hashKey,proto3" json:"hashKey,omitempty"`
	ReadPos              int64      `protobuf:"varint,5,opt,name=readPos,proto3" json:"readPos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{13}
}
func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (dst *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(dst, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetOp() Command_Op {
	if m != nil {
		return m.Op
	}
	return Command_PUSH
}

func (m *Command) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Command) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Command) GetHashKey() []byte {
	if m != nil {
		return m.HashKey
	}
	return nil
}

func (m *Command) GetReadPos() int64 {
	if m != nil {
		return m.ReadPos
	}
	return 0
}

type KeepAliveRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveRequest) Reset()         { *m = KeepAliveRequest{} }
func (m *KeepAliveRequest) String() string { return proto.CompactTextString(m) }
func (*KeepAliveRequest) ProtoMessage()    {}
func (*KeepAliveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{14}
}
func (m *KeepAliveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveRequest.Unmarshal(m, b)
}
func (m *KeepAliveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveRequest.Marshal(b, m, deterministic)
}
func (dst *KeepAliveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveRequest.Merge(dst, src)
}
func (m *KeepAliveRequest) XXX_Size() int {
	return xxx_messageInfo_KeepAliveRequest.Size(m)
}
func (m *KeepAliveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveRequest proto.InternalMessageInfo

type KeepAliveReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveReply) Reset()         { *m = KeepAliveReply{} }
func (m *KeepAliveReply) String() string { return proto.CompactTextString(m) }
func (*KeepAliveReply) ProtoMessage()    {}
func (*KeepAliveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{15}
}
func (m *KeepAliveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveReply.Unmarshal(m, b)
}
func (m *KeepAliveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveReply.Marshal(b, m, deterministic)
}
func (dst *KeepAliveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveReply.Merge(dst, src)
}
func (m *KeepAliveReply) XXX_Size() int {
	return xxx_messageInfo_KeepAliveReply.Size(m)
}
func (m *KeepAliveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveReply.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveReply proto.InternalMessageInfo

type GetStateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStateRequest) Reset()         { *m = GetStateRequest{} }
func (m *GetStateRequest) String() string { return proto.CompactTextString(m) }
func (*GetStateRequest) ProtoMessage()    {}
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{16}
}
func (m *GetStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStateRequest.Unmarshal(m, b)
}
func (m *GetStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStateRequest.Marshal(b, m, deterministic)
}
func (dst *GetStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateRequest.Merge(dst, src)
}
func (m *GetStateRequest) XXX_Size() int {
	return xxx_messageInfo_GetStateRequest.Size(m)
}
func (m *GetStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateRequest proto.InternalMessageInfo

type GetStateReply struct {
	State                uint32   `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStateReply) Reset()         { *m = GetStateReply{} }
func (m *GetStateReply) String() string { return proto.CompactTextString(m) }
func (*GetStateReply) ProtoMessage()    {}
func (*GetStateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{17}
}
func (m *GetStateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStateReply.Unmarshal(m, b)
}
func (m *GetStateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStateReply.Marshal(b, m, deterministic)
}
func (dst *GetStateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateReply.Merge(dst, src)
}
func (m *GetStateReply) XXX_Size() int {
	return xxx_messageInfo_GetStateReply.Size(m)
}
func (m *GetStateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateReply proto.InternalMessageInfo

func (m *GetStateReply) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

type WatchStateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchStateRequest) Reset()         { *m = WatchStateRequest{} }
func (m *WatchStateRequest) String() string { return proto.CompactTextString(m) }
func (*WatchStateRequest) ProtoMessage()    {}
func (*WatchStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{18}
}
func (m *WatchStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchStateRequest.Unmarshal(m, b)
}
func (m *WatchStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchStateRequest.Marshal(b, m, deterministic)
}
func (dst *WatchStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchStateRequest.Merge(dst, src)
}
func (m *WatchStateRequest) XXX_Size() int {
	return xxx_messageInfo_WatchStateRequest.Size(m)
}
func (m *WatchStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WatchStateRequest proto.InternalMessageInfo

type WatchStateReply struct {
	State                uint32   `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchStateReply) Reset()         { *m = WatchStateReply{} }
func (m *WatchStateReply) String() string { return proto.CompactTextString(m) }
func (*WatchStateReply) ProtoMessage()    {}
func (*WatchStateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_diskqueue_4700a647b0f7ddf4, []int{19}
}
func (m *WatchStateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchStateReply.Unmarshal(m, b)
}
func (m *WatchStateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchStateReply.Marshal(b, m, deterministic)
}
func (dst *WatchStateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchStateReply.Merge(dst, src)
}
func (m *WatchStateReply) XXX_Size() int {
	return xxx_messageInfo_WatchStateReply.Size(m)
}
func (m *WatchStateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchStateReply.DiscardUnknown(m)
}

var xxx_messageInfo_WatchStateReply proto.InternalMessageInfo

func (m *WatchStateReply) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "diskqueue.Message")
	proto.RegisterType((*PushRequest)(nil), "diskqueue.PushRequest")
	proto.RegisterType((*PushReply)(nil), "diskqueue.PushReply")
	proto.RegisterType((*PopRequest)(nil), "diskqueue.PopRequest")
	proto.RegisterType((*PopReply)(nil), "diskqueue.PopReply")
	proto.RegisterType((*AckRequest)(nil), "diskqueue.AckRequest")
	proto.RegisterType((*AckReply)(nil), "diskqueue.AckReply")
	proto.RegisterType((*JoinRequest)(nil), "diskqueue.JoinRequest")
	proto.RegisterType((*JoinReply)(nil), "diskqueue.JoinReply")
	proto.RegisterType((*LeaveRequest)(nil), "diskqueue.LeaveRequest")
	proto.RegisterType((*LeaveReply)(nil), "diskqueue.LeaveReply")
	proto.RegisterType((*SnapshotRequest)(nil), "diskqueue.SnapshotRequest")
	proto.RegisterType((*SnapshotReply)(nil), "diskqueue.SnapshotReply")
	proto.RegisterType((*Command)(nil), "diskqueue.Command")
	proto.RegisterType((*KeepAliveRequest)(nil), "diskqueue.KeepAliveRequest")
	proto.RegisterType((*KeepAliveReply)(nil), "diskqueue.KeepAliveReply")
	proto.RegisterType((*GetStateRequest)(nil), "diskqueue.GetStateRequest")
	proto.RegisterType((*GetStateReply)(nil), "diskqueue.GetStateReply")
	proto.RegisterType((*WatchStateRequest)(nil), "diskqueue.WatchStateRequest")
	proto.RegisterType((*WatchStateReply)(nil), "diskqueue.WatchStateReply")
	proto.RegisterEnum("diskqueue.Command_Op", Command_Op_name, Command_Op_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ tr.Server
var _ tr.ClientConn
var _ tropt.CallOption

type DiskqueueGrpcClient interface {
	Push(ctx context.Context, in *PushRequest, opts ...tropt.CallOption) (*PushReply, error)
	Pop(ctx context.Context, in *PopRequest, opts ...tropt.CallOption) (*PopReply, error)
	Ack(ctx context.Context, in *AckRequest, opts ...tropt.CallOption) (*AckReply, error)
	Join(ctx context.Context, in *JoinRequest, opts ...tropt.CallOption) (*JoinReply, error)
	Leave(ctx context.Context, in *LeaveRequest, opts ...tropt.CallOption) (*LeaveReply, error)
	Snapshot(ctx context.Context, in *SnapshotRequest, opts ...tropt.CallOption) (*SnapshotReply, error)
	GetState(ctx context.Context, in *GetStateRequest, opts ...tropt.CallOption) (*GetStateReply, error)
	WatchState(ctx context.Context, in *WatchStateRequest, opts ...tropt.CallOption) (Diskqueue_WatchStateClient, error)
}

type diskqueueGrpcClient struct {
	cc tr.ClientConn
}

func NewDiskqueueGrpcClient(cc tr.ClientConn) DiskqueueGrpcClient {
	return &diskqueueGrpcClient{cc}
}

func (c *diskqueueGrpcClient) Push(ctx context.Context, in *PushRequest, opts ...tropt.CallOption) (*PushReply, error) {
	out := new(PushReply)
	err := c.cc.Invoke(ctx, "/diskqueue.Diskqueue/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskqueueGrpcClient) Pop(ctx context.Context, in *PopRequest, opts ...tropt.CallOption) (*PopReply, error) {
	out := new(PopReply)
	err := c.cc.Invoke(ctx, "/diskqueue.Diskqueue/Pop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskqueueGrpcClient) Ack(ctx context.Context, in *AckRequest, opts ...tropt.CallOption) (*AckReply, error) {
	out := new(AckReply)
	err := c.cc.Invoke(ctx, "/diskqueue.Diskqueue/Ack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskqueueGrpcClient) Join(ctx context.Context, in *JoinRequest, opts ...tropt.CallOption) (*JoinReply, error) {
	out := new(JoinReply)
	err := c.cc.Invoke(ctx, "/diskqueue.Diskqueue/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskqueueGrpcClient) Leave(ctx context.Context, in *LeaveRequest, opts ...tropt.CallOption) (*LeaveReply, error) {
	out := new(LeaveReply)
	err := c.cc.Invoke(ctx, "/diskqueue.Diskqueue/Leave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskqueueGrpcClient) Snapshot(ctx context.Context, in *SnapshotRequest, opts ...tropt.CallOption) (*SnapshotReply, error) {
	out := new(SnapshotReply)
	err := c.cc.Invoke(ctx, "/diskqueue.Diskqueue/Snapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskqueueGrpcClient) GetState(ctx context.Context, in *GetStateRequest, opts ...tropt.CallOption) (*GetStateReply, error) {
	out := new(GetStateReply)
	err := c.cc.Invoke(ctx, "/diskqueue.Diskqueue/GetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskqueueGrpcClient) WatchState(ctx context.Context, in *WatchStateRequest, opts ...tropt.CallOption) (Diskqueue_WatchStateClient, error) {
	stream, err := c.cc.NewStream(ctx, DiskqueueGrpcServiceDesc, 0, "/diskqueue.Diskqueue/WatchState", opts...)
	if err != nil {
		return nil, err
	}
	x := &diskqueueWatchStateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type diskqueueGrpcServiceDesc struct {
	desc *grpc.ServiceDesc
}

func (d *diskqueueGrpcServiceDesc) Desc() interface{} {
	return d.desc
}

var DiskqueueGrpcServiceDesc = &diskqueueGrpcServiceDesc{&_Diskqueue_serviceDesc}

// Reference imports to suppress errors if they are not otherwise used.
var _ context1.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// DiskqueueClient is the client API for Diskqueue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiskqueueClient interface {
	Push(ctx context1.Context, in *PushRequest, opts ...grpc1.CallOption) (*PushReply, error)
	Pop(ctx context1.Context, in *PopRequest, opts ...grpc1.CallOption) (*PopReply, error)
	Ack(ctx context1.Context, in *AckRequest, opts ...grpc1.CallOption) (*AckReply, error)
	Join(ctx context1.Context, in *JoinRequest, opts ...grpc1.CallOption) (*JoinReply, error)
	Leave(ctx context1.Context, in *LeaveRequest, opts ...grpc1.CallOption) (*LeaveReply, error)
	Snapshot(ctx context1.Context, in *SnapshotRequest, opts ...grpc1.CallOption) (*SnapshotReply, error)
	// rpc KeepAlive   (stream KeepAliveRequest)   returns (stream KeepAliveReply)     {}
	GetState(ctx context1.Context, in *GetStateRequest, opts ...grpc1.CallOption) (*GetStateReply, error)
	WatchState(ctx context1.Context, in *WatchStateRequest, opts ...grpc1.CallOption) (Diskqueue_WatchStateClient, error)
}

type diskqueueClient struct {
	cc *grpc1.ClientConn
}

func NewDiskqueueClient(cc *grpc1.ClientConn) DiskqueueClient {
	return &diskqueueClient{cc}
}

func (c *diskqueueClient) Push(ctx context1.Context, in *PushRequest, opts ...grpc1.CallOption) (*PushReply, error) {
	out := new(PushReply)
	err := c.cc.Invoke(ctx, "/diskqueue.Diskqueue/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskqueueClient) Pop(ctx context1.Context, in *PopRequest, opts ...grpc1.CallOption) (*PopReply, error) {
	out := new(PopReply)
	err := c.cc.Invoke(ctx, "/diskqueue.Diskqueue/Pop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskqueueClient) Ack(ctx context1.Context, in *AckRequest, opts ...grpc1.CallOption) (*AckReply, error) {
	out := new(AckReply)
	err := c.cc.Invoke(ctx, "/diskqueue.Diskqueue/Ack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskqueueClient) Join(ctx context1.Context, in *JoinRequest, opts ...grpc1.CallOption) (*JoinReply, error) {
	out := new(JoinReply)
	err := c.cc.Invoke(ctx, "/diskqueue.Diskqueue/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskqueueClient) Leave(ctx context1.Context, in *LeaveRequest, opts ...grpc1.CallOption) (*LeaveReply, error) {
	out := new(LeaveReply)
	err := c.cc.Invoke(ctx, "/diskqueue.Diskqueue/Leave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskqueueClient) Snapshot(ctx context1.Context, in *SnapshotRequest, opts ...grpc1.CallOption) (*SnapshotReply, error) {
	out := new(SnapshotReply)
	err := c.cc.Invoke(ctx, "/diskqueue.Diskqueue/Snapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskqueueClient) GetState(ctx context1.Context, in *GetStateRequest, opts ...grpc1.CallOption) (*GetStateReply, error) {
	out := new(GetStateReply)
	err := c.cc.Invoke(ctx, "/diskqueue.Diskqueue/GetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskqueueClient) WatchState(ctx context1.Context, in *WatchStateRequest, opts ...grpc1.CallOption) (Diskqueue_WatchStateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Diskqueue_serviceDesc.Streams[0], "/diskqueue.Diskqueue/WatchState", opts...)
	if err != nil {
		return nil, err
	}
	x := &diskqueueWatchStateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Diskqueue_WatchStateClient interface {
	Recv() (*WatchStateReply, error)
	grpc1.ClientStream
}

type diskqueueWatchStateClient struct {
	grpc1.ClientStream
}

func (x *diskqueueWatchStateClient) Recv() (*WatchStateReply, error) {
	m := new(WatchStateReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DiskqueueServer is the server API for Diskqueue service.
type DiskqueueServer interface {
	Push(context1.Context, *PushRequest) (*PushReply, error)
	Pop(context1.Context, *PopRequest) (*PopReply, error)
	Ack(context1.Context, *AckRequest) (*AckReply, error)
	Join(context1.Context, *JoinRequest) (*JoinReply, error)
	Leave(context1.Context, *LeaveRequest) (*LeaveReply, error)
	Snapshot(context1.Context, *SnapshotRequest) (*SnapshotReply, error)
	// rpc KeepAlive   (stream KeepAliveRequest)   returns (stream KeepAliveReply)     {}
	GetState(context1.Context, *GetStateRequest) (*GetStateReply, error)
	WatchState(*WatchStateRequest, Diskqueue_WatchStateServer) error
}

func RegisterDiskqueueServer(s *grpc1.Server, srv DiskqueueServer) {
	s.RegisterService(&_Diskqueue_serviceDesc, srv)
}

func _Diskqueue_Push_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskqueueServer).Push(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diskqueue.Diskqueue/Push",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(DiskqueueServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diskqueue_Pop_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskqueueServer).Pop(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diskqueue.Diskqueue/Pop",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(DiskqueueServer).Pop(ctx, req.(*PopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diskqueue_Ack_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskqueueServer).Ack(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diskqueue.Diskqueue/Ack",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(DiskqueueServer).Ack(ctx, req.(*AckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diskqueue_Join_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskqueueServer).Join(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diskqueue.Diskqueue/Join",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(DiskqueueServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diskqueue_Leave_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskqueueServer).Leave(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diskqueue.Diskqueue/Leave",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(DiskqueueServer).Leave(ctx, req.(*LeaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diskqueue_Snapshot_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskqueueServer).Snapshot(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diskqueue.Diskqueue/Snapshot",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(DiskqueueServer).Snapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diskqueue_GetState_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskqueueServer).GetState(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diskqueue.Diskqueue/GetState",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(DiskqueueServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diskqueue_WatchState_Handler(srv interface{}, stream grpc1.ServerStream) error {
	m := new(WatchStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DiskqueueServer).WatchState(m, &diskqueueWatchStateServer{stream})
}

type Diskqueue_WatchStateServer interface {
	Send(*WatchStateReply) error
	grpc1.ServerStream
}

type diskqueueWatchStateServer struct {
	grpc1.ServerStream
}

func (x *diskqueueWatchStateServer) Send(m *WatchStateReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Diskqueue_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "diskqueue.Diskqueue",
	HandlerType: (*DiskqueueServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _Diskqueue_Push_Handler,
		},
		{
			MethodName: "Pop",
			Handler:    _Diskqueue_Pop_Handler,
		},
		{
			MethodName: "Ack",
			Handler:    _Diskqueue_Ack_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _Diskqueue_Join_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _Diskqueue_Leave_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _Diskqueue_Snapshot_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _Diskqueue_GetState_Handler,
		},
	},
	Streams: []grpc1.StreamDesc{
		{
			StreamName:    "WatchState",
			Handler:       _Diskqueue_WatchState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "diskqueue.proto",
}

func init() { proto.RegisterFile("diskqueue.proto", fileDescriptor_diskqueue_4700a647b0f7ddf4) }

var fileDescriptor_diskqueue_4700a647b0f7ddf4 = []byte{
	// 617 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x4e, 0xdb, 0x4c,
	0x10, 0x8d, 0x1d, 0x07, 0xdb, 0x93, 0x40, 0xc2, 0x12, 0xf8, 0x2c, 0x7f, 0x5c, 0xa0, 0x95, 0x68,
	0xb9, 0xa8, 0x50, 0x05, 0x52, 0x45, 0xa5, 0xde, 0xb8, 0xa4, 0x3f, 0x40, 0x5b, 0xa2, 0x45, 0x6d,
	0xaf, 0xb7, 0xf1, 0x96, 0x58, 0x89, 0xbd, 0x8b, 0xbd, 0xa9, 0x94, 0x67, 0xea, 0xeb, 0xf5, 0x01,
	0x2a, 0xaf, 0xff, 0x93, 0x80, 0xd4, 0xbb, 0xcc, 0x99, 0x39, 0x67, 0xc6, 0x33, 0x67, 0x03, 0x7d,
	0x3f, 0x48, 0x66, 0x0f, 0x0b, 0xb6, 0x60, 0xa7, 0x22, 0xe6, 0x92, 0x23, 0xbb, 0x04, 0x30, 0x03,
	0xf3, 0x33, 0x4b, 0x12, 0x7a, 0xcf, 0xd0, 0x0e, 0xe8, 0x57, 0x23, 0x47, 0x3b, 0xd2, 0x4e, 0x0c,
	0xa2, 0x5f, 0x8d, 0x10, 0x02, 0xc3, 0xa7, 0x92, 0x3a, 0xfa, 0x91, 0x76, 0xd2, 0x23, 0xea, 0x37,
	0x72, 0xc0, 0x9c, 0xd2, 0x64, 0x7a, 0xc3, 0x96, 0x4e, 0x5b, 0xc1, 0x45, 0x88, 0x0e, 0xc1, 0x96,
	0x41, 0xc8, 0x12, 0x49, 0x43, 0xe1, 0x18, 0x47, 0xda, 0x49, 0x9b, 0x54, 0x00, 0x5e, 0x40, 0x77,
	0xbc, 0x48, 0xa6, 0x84, 0x3d, 0x2c, 0x58, 0x22, 0xd1, 0x10, 0x3a, 0x92, 0x8b, 0x60, 0xa2, 0xba,
	0xd9, 0x24, 0x0b, 0xfe, 0xb1, 0x21, 0x86, 0x5e, 0x70, 0x1f, 0xf1, 0x98, 0xbd, 0x0f, 0xe6, 0x92,
	0xc5, 0xaa, 0xa7, 0x45, 0x1a, 0x18, 0xee, 0x82, 0x9d, 0xb5, 0x15, 0xf3, 0x25, 0x7e, 0x03, 0x30,
	0xe6, 0xe2, 0xe9, 0x11, 0x1c, 0x30, 0x23, 0xc6, 0x7c, 0x6f, 0x32, 0x53, 0x53, 0x58, 0xa4, 0x08,
	0xf1, 0x05, 0x58, 0x8a, 0x2d, 0xe6, 0x4b, 0xf4, 0x02, 0xcc, 0x30, 0x5b, 0x9a, 0x62, 0x77, 0xcf,
	0xd0, 0x69, 0xb5, 0xe2, 0x7c, 0x9d, 0xa4, 0x28, 0xc1, 0x17, 0x00, 0xde, 0x64, 0xf6, 0x74, 0xdf,
	0x21, 0x74, 0xc2, 0xe4, 0xfe, 0x6a, 0xa4, 0xba, 0x1a, 0x24, 0x0b, 0x30, 0x80, 0xa5, 0x98, 0xe9,
	0xf4, 0x1e, 0x74, 0xaf, 0x79, 0x10, 0x15, 0x32, 0x2e, 0x58, 0x31, 0xfd, 0x29, 0x3d, 0xdf, 0x8f,
	0x73, 0xa5, 0x32, 0x46, 0x07, 0xb0, 0x15, 0x71, 0x9f, 0xe5, 0x6a, 0x36, 0xc9, 0xa3, 0x74, 0x1b,
	0x99, 0x44, 0xaa, 0xf7, 0x0c, 0x7a, 0x9f, 0x18, 0xfd, 0xc5, 0x0a, 0xc1, 0x8a, 0xa4, 0x35, 0x48,
	0x3d, 0x80, 0xbc, 0x2e, 0x65, 0xed, 0x42, 0xff, 0x2e, 0xa2, 0x22, 0x99, 0x72, 0x99, 0x13, 0x71,
	0x1f, 0xb6, 0x2b, 0x28, 0xad, 0xf9, 0xad, 0x81, 0x79, 0xc9, 0xc3, 0x90, 0x46, 0x3e, 0x3a, 0x06,
	0x9d, 0x0b, 0xa5, 0xb8, 0x73, 0xb6, 0x5f, 0x5b, 0x52, 0x9e, 0x3f, 0xbd, 0x15, 0x44, 0xe7, 0xa2,
	0x5a, 0x8a, 0xbe, 0xc9, 0x0f, 0xed, 0xcd, 0x7e, 0x30, 0x9a, 0x7e, 0x70, 0xc0, 0x8c, 0x19, 0xf5,
	0xc7, 0x3c, 0x71, 0x3a, 0xca, 0x7e, 0x45, 0x88, 0xff, 0x07, 0xfd, 0x56, 0x20, 0x0b, 0x8c, 0xf1,
	0xd7, 0xbb, 0x8f, 0x83, 0x16, 0xea, 0x82, 0xe9, 0x8d, 0xbe, 0x79, 0x5f, 0x2e, 0xdf, 0x0d, 0x34,
	0x8c, 0x60, 0x70, 0xc3, 0x98, 0xf0, 0xe6, 0x41, 0xb9, 0x0b, 0x3c, 0x80, 0x9d, 0x1a, 0x96, 0x7f,
	0xf7, 0x07, 0x26, 0xef, 0x24, 0x95, 0x65, 0xd1, 0x31, 0x6c, 0x57, 0x50, 0xea, 0x8a, 0x21, 0x74,
	0x92, 0x34, 0x52, 0x9f, 0xbb, 0x4d, 0xb2, 0x00, 0xef, 0xc1, 0xee, 0x77, 0x2a, 0x27, 0xd3, 0x06,
	0xf7, 0x39, 0xf4, 0xeb, 0xe0, 0xa3, 0xec, 0xb3, 0x3f, 0x6d, 0xb0, 0x47, 0xc5, 0xd6, 0xd0, 0x2b,
	0x30, 0x52, 0x3b, 0xa3, 0x83, 0xda, 0x26, 0x6b, 0xcf, 0xca, 0x1d, 0xae, 0xe1, 0xe9, 0xec, 0x2d,
	0x74, 0x0e, 0xed, 0x31, 0x17, 0xa8, 0x7e, 0x80, 0xea, 0x25, 0xb8, 0x7b, 0xab, 0x70, 0x49, 0xf2,
	0x26, 0xb3, 0x06, 0xa9, 0xb2, 0x71, 0x83, 0x54, 0x7a, 0xb4, 0x95, 0x4e, 0x98, 0x5a, 0xac, 0x31,
	0x61, 0xcd, 0xb6, 0x8d, 0x09, 0x2b, 0x2f, 0xb6, 0xd0, 0x6b, 0xe8, 0x28, 0x97, 0xa1, 0xff, 0x6a,
	0x05, 0x75, 0x7f, 0xba, 0xfb, 0xeb, 0x89, 0x8c, 0xfa, 0x16, 0xac, 0xc2, 0x7f, 0xc8, 0xad, 0x15,
	0xad, 0xf8, 0xd4, 0x75, 0x36, 0xe6, 0x4a, 0x8d, 0xe2, 0x96, 0x0d, 0x8d, 0x95, 0x9b, 0x37, 0x34,
	0x1a, 0xc7, 0xc7, 0x2d, 0x74, 0x0d, 0x50, 0xdd, 0x14, 0x1d, 0xd6, 0x2a, 0xd7, 0xee, 0xef, 0xba,
	0x8f, 0x64, 0x95, 0xd2, 0x4b, 0xed, 0xc7, 0x96, 0xfa, 0x9f, 0x3e, 0xff, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0x63, 0xd6, 0x0f, 0x74, 0xba, 0x05, 0x00, 0x00,
}
